#!/bin/bash
set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}=======================================${NC}"
echo -e "${BLUE}   EthrAUTH - Deployment Wizard        ${NC}"
echo -e "${BLUE}=======================================${NC}"

# Function to generate random password
generate_password() {
    openssl rand -base64 24 | tr -d '/+' | cut -c1-16
}

# Prompt for User Input
echo -e "\n${YELLOW}Step 1: Configuration${NC}"

# 1. Base Domain
read -p "Enter your base domain (e.g., example.com): " BASE_DOMAIN
if [ -z "$BASE_DOMAIN" ]; then
    echo "Base domain is required."
    exit 1
fi

# 2. Keycloak Subdomain
read -p "Enter Keycloak subdomain (default: auth.$BASE_DOMAIN): " KEYCLOAK_SUBDOMAIN
KEYCLOAK_HOSTNAME=${KEYCLOAK_SUBDOMAIN:-auth.$BASE_DOMAIN}
echo -e "${GREEN}Using Keycloak Hostname: $KEYCLOAK_HOSTNAME${NC}"

# 3. Admin Email (for Certs/Admin)
read -p "Enter Admin Email (e.g., admin@$BASE_DOMAIN): " ADMIN_EMAIL
if [ -z "$ADMIN_EMAIL" ]; then
    echo "Admin email is required."
    exit 1
fi

# 4. Passwords
read -sp "Enter Keycloak Admin Password (leave blank to generate): " KC_ADMIN_PASS
echo ""
if [ -z "$KC_ADMIN_PASS" ]; then
    KC_ADMIN_PASS=$(generate_password)
    echo -e "${GREEN}Generated Keycloak Admin Password: $KC_ADMIN_PASS${NC}"
fi

read -sp "Enter PostgreSQL Password (leave blank to generate): " PG_PASS
echo ""
if [ -z "$PG_PASS" ]; then
    PG_PASS=$(generate_password)
    echo -e "${GREEN}Generated PostgreSQL Password: $PG_PASS${NC}"
fi

# 5. EthrSITE Integration (Optional)
echo -e "\n${YELLOW}Step 2: Integration (Optional)${NC}"
read -p "Enter EthrSITE URL (e.g. https://site.$BASE_DOMAIN) [optional]: " ETHRSITE_URL
ETHRSITE_URL=${ETHRSITE_URL:-"https://site.$BASE_DOMAIN"}

read -p "Enter EthrSITE Client ID (default: ethrsite-frontend): " ETHRSITE_CLIENT_ID
ETHRSITE_CLIENT_ID=${ETHRSITE_CLIENT_ID:-ethrsite-frontend}

read -sp "Enter EthrSITE Client Secret (leave blank to generate): " ETHRSITE_CLIENT_SECRET
echo ""
if [ -z "$ETHRSITE_CLIENT_SECRET" ]; then
    ETHRSITE_CLIENT_SECRET=$(generate_password)
    echo -e "${GREEN}Generated Client Secret: $ETHRSITE_CLIENT_SECRET${NC}"
fi


# Generate .env file
echo -e "\n${YELLOW}Step 3: Generating Configuration...${NC}"

cat > .env <<EOF
# EthrAUTH Environment Configuration
# Generated by setup.sh on $(date)

# Keycloak Configuration
KEYCLOAK_ADMIN_PASSWORD=$KC_ADMIN_PASS
KEYCLOAK_HOSTNAME=$KEYCLOAK_HOSTNAME
KEYCLOAK_URL=https://$KEYCLOAK_HOSTNAME
KEYCLOAK_ADMIN_URL=https://$KEYCLOAK_HOSTNAME

# PostgreSQL Database
POSTGRES_PASSWORD=$PG_PASS

# EthrSITE Integration
ETHRSITE_URL=$ETHRSITE_URL
ETHRSITE_CLIENT_ID=$ETHRSITE_CLIENT_ID
ETHRSITE_CLIENT_SECRET=$ETHRSITE_CLIENT_SECRET

# Admin Email (Metadata)
ADMIN_EMAIL=$ADMIN_EMAIL
EOF

echo -e "${GREEN}.env file created successfully!${NC}"

# Git Initialization
echo -e "\n${YELLOW}Step 4: Infrastructure as Code (Git Setup)${NC}"

if [ ! -d ".git" ]; then
    echo "Initializing Git repository..."
    git init
    git branch -M main
else
    echo "Git repository already initialized."
fi

echo "Adding deployment files to Git..."
# Ensure .gitignore exists
if [ ! -f ".gitignore" ]; then
    echo ".env" > .gitignore
    echo "docker-compose.override.yml" >> .gitignore
fi

git add .gitignore docker-compose.yml docker-compose.prod.yml .env.example README.md setup.sh

if git diff --cached --quiet; then
    echo "No changes to commit."
else
    git commit -m "chore: initial setup via agent wizard"
    echo -e "${GREEN}Configuration committed to Git.${NC}"
fi

echo -e "\n${BLUE}=======================================${NC}"
echo -e "${GREEN}   Setup Complete!                     ${NC}"
echo -e "${BLUE}=======================================${NC}"
echo -e "To deploy, run:"
echo -e "  ${YELLOW}docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d${NC}"
echo -e "\nAccess Keycloak at: https://$KEYCLOAK_HOSTNAME"
echo -e "Admin User: admin"
echo -e "Admin Password: (saved in .env)"
